### ISSUE TITLE
Configuration of repository

### ISSUE THREAD

**Issue by bulentrahimkazanci** [SWEZenith/Fall2017Swe574-Zenith#1]
- Labels will be created.
- Collaborators will be added.
- Timesheet format will be created for personal logs.
- Readme file will be created.
- Badges will be created.
- Issue format will be created.
- Project will be created.

**Comment by yaseminalpay** [comment]
Is it possible to move this repo to an organization? so that it will not belong to a single person but all members? (for reducing the effort of owner in case something should be changed in the repo)

steps:
1- create an organization by clicking your profile settings
2- go to settings of this repo-> danger zone -> click "transfer ownership" -> give the name of the repo and the name of the organization to be transferred

**Comment by bulentrahimkazanci** [comment]
@yaseminalpay As you suggested in previous comment, it is better way to deal with changes on repository so I moved repository into a new organization.
